apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../app


namespace: prod

images:
  - name: fastapi-app
    newName: ghcr.io/a9mansoo/kubernetes-deployment/fastapi-app
    newTag: "2.0.0"
  
  - name: frontend-react
    newName: ghcr.io/a9mansoo/kubernetes-deployment/frontend-react
    newTag: "2.0.0"
