apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../app


namespace: prod

images:
  - name: ghcr.io/a9mansoo/kubernetes-deployment/fastapi-app
    newTag: "v2.0.0"
  
  - name: ghcr.io/a9mansoo/kubernetes-deployment/frontend-react
    newTag: "v2.0.0"
