apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: prod
  labels:
    component: frontend
    type: blue
  
spec:
  selector:
    app: frontend-react-pod
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
    

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: prod
  labels:
    component: backend-service
spec:
  selector:
    app: fastapi-pod
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
