apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: prod
  labels:
    app: fastapi-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-pod
  template:
    metadata:
      labels:
        app: fastapi-pod
    spec:
      containers:
        - name: backend-app
          image: fastapi-app
          envFrom:
            - configMapRef:
                - name: backend-configmap
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /hlth/ready
              port: 8000
          livenessProbe:
            httpGet:
              path: /hlth/live
              port: 8000
      restartPolicy: Always
