name: Build Project Images

on:
    push:

jobs:
    build_backend:
        uses: ./.github/workflows/build-images.yml
        with:
            BASE_IMAGE_NAME: "ghcr.io/${{ github.repository }}/fastapi-app"
    
    build_frontend:
        uses: ./.github/workflows/build-images.yml
        with:
            BASE_IMAGE_NAME: "ghcr.io/${{ github.repository }}/frontend-react"