name: Build Docker Images Reusable Workflow


on:
    workflow_call:
        inputs:
            BASE_IMAGE_NAME:
                type: string
                description: An Image Name that will be used while creating the image
                required: true
            
            BUILD_CONTEXT:
                type: string
                description: The build context to use when building the image
                required: true
            
            IMAGE_PATH:
                type: string
                description: The path to the dockerfile to build, assume it is starting from root dir
                required: true



jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
            
            - name: Read Metadata
              uses: docker/metadata-action@v6
              id: image-metadata
              with:
                images: |
                  ${{ inputs.BASE_IMAGE_NAME }}
                tags: |
                  type=ref,event=pr
                  type=ref,event=branch
            
            - name: Output Metadata
              run: |
                echo "${{ steps.image-metadata.outputs.tags }}"
            
            - name: Build Image
              uses: docker/build-push-action@v7
              with:
                context: ${{ inputs.BUILD_CONTEXT }}
                push: false
                file: ${{ inputs.IMAGE_PATH }}
                tags: ${{ steps.image-metadata.outputs.tags }}
