name: Build Project Images

on:
    push:
        branches:
            - master
    
    pull_request:
        types: [opened, reopened, synchronize]
    
    release:
        types: [published]

permissions:
    contents: read
    packages: write


concurrency:
    group: build-project-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build_backend:
        uses: ./.github/workflows/build-images.yml
        with:
            BASE_IMAGE_NAME: "ghcr.io/${{ github.repository }}/fastapi-app"
            BUILD_CONTEXT: "."
            IMAGE_PATH: "docker/backend.dockerfile"
        secrets:
            inherit
    
    build_frontend:
        uses: ./.github/workflows/build-images.yml
        with:
            BASE_IMAGE_NAME: "ghcr.io/${{ github.repository }}/frontend-react"
            BUILD_CONTEXT: "."
            IMAGE_PATH: "docker/frontend.dockerfile"
        secrets:
            inherit
