name: Deploy Application


on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          options:
            - development
            - production


jobs:
    setup_and_run_app:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout k8s
              uses: actions/checkout@v4
            
            - name: Setup Minikube
              uses: medyagh/setup-minikube@v0.0.20
              with:
                minikube-version: '1.36.0'
            
            - name: Setup Cluster Environment
              working-directory: "k8s/environments"
              run: |
                kubectl apply -f prod/prod_namespace.yml
            
            - name: Build Resources with Kustomize
              working-directory: "k8s/environments"
              run: |
                 kubectl apply -k prod
            
            - name: Wait for Deployments to be ready
              run: |
                 kubectl rollout status deploy/backend
                 kubectl rollout status deploy/frontend

            - name: Print Deployment health
              run: |
                kubectl get deploy -n prod
            
            - name: Start Frontend Service
              run: | 
                 minikube service frontend-service --namespace=prod --url
