name: Deploy Application In Minikube Demo


on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          options:
            - production


jobs:
    setup_and_run_app:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout k8s
              uses: actions/checkout@v4
            
            - name: Setup Minikube
              uses: medyagh/setup-minikube@v0.0.20
              with:
                minikube-version: '1.36.0'
            
            - name: Setup Cluster Environment
              working-directory: "k8s/environments"
              run: |
                kubectl apply -f prod/prod_namespace.yml
            
            - name: Build Resources with Kustomize
              working-directory: "k8s/environments"
              run: |
                 kubectl apply -k prod
            
            - name: Wait for Deployments to be ready
              id: deployment-status
              run: |
                 kubectl rollout status deploy/backend --namespace=prod --timeout=60s
                 kubectl rollout status deploy/frontend --namespace=prod --timeout=60s

            - name: Print Deployment health
              run: |
                kubectl get deploy -n prod
            
            - name: Start Frontend Service
              id: frontend-service
              run: | 
                 SERVICE_URL=$(minikube service frontend-service --namespace=prod --url)
                 echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV
            
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.10'
            
            - name: Install Playwright
              run: |
                pip install playwright
                playwright install
            
            - name: Retrieve UI Screenshot
              id: smoke-test
              run: |
                python - <<EOF
                from playwright.sync_api import sync_playwright
                import os
                url = os.environ["SERVICE_URL"]
                with sync_playwright() as p:
                  browser = p.chromium.launch()
                  page = browser.new_page()
                  page.goto(url, wait_until="networkidle")
                  page.screenshot(path="ui.png", full_page=True)
                  browser.close()
                EOF
                exit 1

            - name: Archive UI Page
              uses: actions/upload-artifact@v7
              id: artifact-upload
              with:
                path: ui.png
                archive: false
            
            - name: Summarize Deployment
              if: ${{ !cancelled() }}
              uses: actions/github-script@v8
              with:
                script: |
                  let rolloutStatus = "${{ steps.deployment-status.outcome }}"
                  let serviceEndpointStatus = "${{steps.frontend-service.outcome }}"
                  let smokeTestStatus = "${{ steps.smoke-test.outcome }}"
                  let uiArtifactUrl = "${{ steps.artifact-upload.outcome }}" === 'success' ? "${{ steps.artifact-upload.artifact-url }}": 'NO URL'

                  let overallStatus = (rolloutStatus === 'success' && smokeTestStatus === 'success') ? '✅ PASSED' : '❌ FAILED'
                  
                  let summary =core.summary.addHeading(`Deployment Status: ${overallStatus}`)
                  .addRaw(`Rollout Status Check: ${rolloutStatus}`)
                  .addRaw(`Service Endpoint Check: ${serviceEndpointStatus}`)
                  .addRaw(`Smoke Tests Status Check: ${smokeTestStatus}`)

                  uiArtifactUrl === 'NO_URL' ? summary.addRaw(`UI Screenshot Artifact URL: ${uiArtifactUrl}`) : summary.addLink('UI Screenshot Artifact URL:', `${uiArtifactUrl}`)
                  summary.write()
