name: Deploy Application As Minikube Demo


on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          options:
            - production


jobs:
    setup_and_run_app:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout k8s
              uses: actions/checkout@v4
            
            - name: Setup Minikube
              uses: medyagh/setup-minikube@v0.0.20
              with:
                minikube-version: '1.36.0'
            
            - name: Setup Cluster Environment
              working-directory: "k8s/environments"
              run: |
                kubectl apply -f prod/prod_namespace.yml
            
            - name: Build Resources with Kustomize
              working-directory: "k8s/environments"
              run: |
                 kubectl apply -k prod
            
            - name: Wait for Deployments to be ready
              run: |
                 kubectl rollout status deploy/backend --namespace=prod
                 kubectl rollout status deploy/frontend --namespace=prod

            - name: Print Deployment health
              run: |
                kubectl get deploy -n prod
            
            - name: Start Frontend Service
              run: | 
                 SERVICE_URL=$(minikube service frontend-service --namespace=prod --url)
                 curl $SERVICE_URL > ui_page.html
                 cat ui_page.html
            
            - name: Archive UI Page
              uses: actions/upload-artifact@v7
              with:
                path: ui_page.html
                archive: false
              
