name: Backend CI

on:
    push:
        branches:
            - master

    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - master
        paths:
          - backend/**


concurrency:
  group: python-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout backend
              uses: actions/checkout@v6
              with:
                show-progress: true
                sparse-checkout: backend
            
            - name: Show files
              run: |
                ls -al ./
            
            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                 python-version-file: "backend/pyproject.toml"
            
            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
            
            - name: Run Black
              working-directory: backend
              run: uv tool run black --check .
    
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout backend
              uses: actions/checkout@v6
              with:
                show-progress: true
                sparse-checkout: backend
            
            - name: Show files
              run: |
                ls -al ./
            
            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                 python-version-file: "backend/pyproject.toml"
            
            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
            
            - name: Run ruff
              working-directory: backend
              run: uv tool run ruff check --output-format=github .
            
    
    test:
        runs-on: ubuntu-latest
        needs: [lint, format]
        permissions:
          contents: read
          pull-requests: write
        steps:
            - name: Checkout backend
              uses: actions/checkout@v6
              with:
                show-progress: true
                sparse-checkout: backend
            
            - name: Show files
              run: |
                ls -al ./
            
            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version-file: "backend/pyproject.toml"
         
            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
            
            - name: Install Dependencies
              working-directory: backend
              run: |
                uv sync --extra test
            
            - name: Run Tests
              working-directory: backend
              run: |
                 uv run pytest --cov-report xml:coverage.xml
            
            - name: Coverage comment
              uses: MishaKav/pytest-coverage-comment@v1
              if: ${{ github.event_name == 'pull_request' }}
              with:
                pytest-xml-coverage-path: ./coverage.xml
