name: Frontend CI

on:
    push:
        branches:
            - master
    
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - frontend/**

jobs:
    quality_gate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            
            - name: Setup node
              uses: actions/setup-node@v6
              with:
                node-version: 20
            
            - name: Install dependencies
              working-directory: frontend/app
              run: |
                npm ci
            
            - name: Format
              working-directory: frontend/app
              run: | 
                npm run format
            
            - name: Lint
              working-directory: frontend/app
              run: | 
                npm run lint
            
            - name: Test
              working-directory: frontend/app
              run: | 
                npm run test
    
    build:
        runs-on: ubuntu-latest
        needs: [quality_gate]
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            
            - name: Setup node
              uses: actions/setup-node@v6
              with:
                node-version: 20
            
            - name: Install dependencies
              working-directory: frontend/app
              run: |
                npm ci
            
            - name: Build
              working-directory: frontend/app
              run: | 
                npm run build
